### ISSUE TITLE
sch (Scholiast) change markup

### ISSUE THREAD

**Issue by funderburkjim** [sanskrit-lexicon/temp_corrections_mw#1]
@gasyoun   We discussed several weeks ago changing MW markup so the 'Sch' was out of `<ls>` tag.  I wanted to go ahead and do this.  Can you recall the comment where we discussed this?

**Comment by gasyoun** [comment]
> Can you recall the comment where we discussed this?

https://github.com/sanskrit-lexicon/PWG/issues/35

**Comment by funderburkjim** [comment]
@gasyoun -- didn't we somewhere discuss *MW*  re moving 'Sch.' out of the Panini literary source markup?

**Comment by gasyoun** [comment]
> didn't we somewhere discuss MW re moving 'Sch.' out of the Panini literary source markup?

We did, but not in https://github.com/sanskrit-lexicon/MWS/issues

https://github.com/sanskrit-lexicon/csl-orig/issues/519#issuecomment-817270127 seem to be

**Comment by funderburkjim** [comment]
These corrections made in csl-orig/v02/mw.txt.

Ref: https://github.com/sanskrit-lexicon/csl-orig/issues/519
